import Head from "next/head";

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <>
        <h1 className="text-center underline text-xl">
          Apollo server and client
        </h1>
      </>
    </>
  );
};

export default HomePage;
