import Head from "next/head";
import { GetStaticProps } from "next";

import {
  initialiseApolloClient,
  addApolloState,
  GET_CHARACTERS,
} from "@/graphql/client";
import CharacterGrid from "@/components/CharacterGrid";
import SpaceshipPassengers, {
  ShipContainer,
} from "@/components/SpaceshipPassengers";

export const getStaticProps: GetStaticProps = async (ctx) => {
  const apolloCLient = initialiseApolloClient();
  await apolloCLient.query({ query: GET_CHARACTERS });

  return addApolloState(apolloCLient, {
    props: {},
  });
};

const HomePage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <ShipContainer>
          <SpaceshipPassengers />
        </ShipContainer>
        <CharacterGrid />
      </>
    </>
  );
};

export default HomePage;
